### ISSUE TITLE
it doesnt work

### ISSUE THREAD

**Issue by jonah-sullivan** [MACBIO/GeoWrap#1]

**Comment by pcav** [comment]
Please provide an explanation. such tickats are useless (and, from a more personal note, I must say rather irritant)

**Comment by jonah-sullivan** [comment]
I discovered that the plugin didn't work on a co-workers computer. I raised the issue to remind myself that I needed to troubleshoot the plugin. I fixed it today, so I'll close the issue.

The problem had to do with calling a subprocess without a console. It's fixed now.

**Comment by pcav** [comment]
Thanks for explaining. before approving I check open tickets, that's the reason of my comment.
